version: '2'

networks:
  demo:

services:
  cassandra:
    image: cassandra:3.10
    container_name: cassandra
    networks:
      demo:
        aliases:
          - cassandra

  app:
    build: .
    container_name: app
    ports:
      - "8888:8888"
    networks:
      - demo
    depends_on:
      - cassandra
