meetup:
    build: .
    container_name: meetup
    ports:
        - "8888:8888"
    links:
      - cassandra:cassandra
cassandra:
  image: cassandra:latest
  container_name: cassandra
  ports:
    - "9042:9042"
